services:
  anime-media-manager:
    build:
      context: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-100}
    volumes:
      - /media:/media
      - ${AMM_ROOT_DIR:-/app/amm-state}/data:/app/data
      - ${AMM_ROOT_DIR:-/app/amm-state}/logs:/app/logs
