"""Application settings and .env persistence.

Notes:
- AMM_* runtime OS environment variables are intentionally ignored.
- Config is loaded from persisted .env file and can be updated from Web UI.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import os
import secrets


def _default_db_url() -> str:
  data_dir = Path('/app/data')
  if data_dir.exists():
    return f"sqlite:///{(data_dir / 'anime_media.db').as_posix()}"
  local_db = Path(__file__).resolve().parent.parent / 'anime_media.db'
  return f"sqlite:///{local_db.as_posix()}"


def _default_env_file() -> Path:
  # Priority:
  # 1) explicit legacy location (/app/.env) when present
  # 2) persistent runtime location (/app/data/.env)
  # 3) local dev repository root (.env)
  legacy = Path('/app/.env')
  if legacy.exists():
    return legacy
  data_dir = Path('/app/data')
  if data_dir.exists():
    return data_dir / '.env'
  return Path(__file__).resolve().parent.parent / '.env'


def _ensure_env_file(path: Path) -> None:
  if path.exists():
    return
  path.parent.mkdir(parents=True, exist_ok=True)
  init_username = "admin"
  init_password = secrets.token_urlsafe(12)
  init_secret = secrets.token_urlsafe(32)
  content = (
    "# Auto-generated by Anime Media Manager on first startup.\n"
    "# Please review and update these values in Web UI if needed.\n"
    f"AMM_AUTH_ENABLED=true\n"
    f"AMM_AUTH_USERNAME={init_username}\n"
    f"AMM_AUTH_PASSWORD={init_password}\n"
    f"AMM_AUTH_SECRET={init_secret}\n"
    "AMM_AUTH_TOKEN_EXPIRE_HOURS=24\n"
  )
  path.write_text(content, encoding='utf-8')


def _parse_bool(v: str | None, default: bool) -> bool:
  if v is None:
    return default
  return v.strip().lower() in {'1', 'true', 'yes', 'on'}


def _parse_int(v: str | None, default: int) -> int:
  if v is None or not str(v).strip():
    return default
  try:
    return int(str(v).strip())
  except ValueError:
    return default


def _parse_float(v: str | None, default: float) -> float:
  if v is None or not str(v).strip():
    return default
  try:
    return float(str(v).strip())
  except ValueError:
    return default


def _read_env_file(path: Path) -> dict[str, str]:
  if not path.exists():
    return {}
  data: dict[str, str] = {}
  for raw in path.read_text(encoding='utf-8').splitlines():
    line = raw.strip()
    if not line or line.startswith('#') or '=' not in line:
      continue
    k, v = line.split('=', 1)
    data[k.strip()] = v.strip()
  return data


def _migrate_legacy_pending_path(path_value: str | None, default_value: str) -> str:
  raw = str(path_value or "").strip()
  if not raw:
    return default_value
  legacy_prefix = "/media/pending/"
  if raw.startswith(legacy_prefix):
    return "/app/pending/" + raw[len(legacy_prefix):]
  return raw


@dataclass
class Settings:
  media_root: str = '/media'
  source_tv: str = '/media/source_tv'
  source_movie: str = '/media/source_movie'
  target_tv: str = '/media/target_tv'
  target_movie: str = '/media/target_movie'
  temp_dir: str = '/media/temp'

  database_url: str = _default_db_url()

  # compatibility: frontend still exposes bangumi key field
  bangumi_api_key: str = ''
  tmdb_api_key: str = ''
  emby_url: str = ''
  emby_api_key: str = ''
  emby_library_ids: str = ''

  movie_fallback_strategy: str = 'auto'
  movie_fallback_hints: str = ''

  stats_ignore_specials: bool = True
  stats_ignore_extras: bool = True
  stats_ignore_trailers_featurettes: bool = True

  auth_enabled: bool = True
  auth_username: str = 'admin'
  auth_password: str = 'admin123'
  auth_secret: str = ''
  auth_token_expire_hours: int = 24

  log_retention_days: int = 14
  log_max_task_files: int = 200
  log_cleanup_interval_seconds: int = 600
  preserve_original_index: bool = True
  max_auto_remap_attempts: int = 3
  special_index_max_digits: int = 3
  pending_jsonl_path: str = '/app/pending/pending.jsonl'
  unprocessed_items_jsonl_path: str = '/app/pending/unprocessed_items.jsonl'
  review_jsonl_path: str = '/app/pending/review.jsonl'
  # Backward-compatible alias. Prefer `unprocessed_items_jsonl_path`.
  unhandled_jsonl_path: str = '/app/pending/unprocessed_items.jsonl'
  use_file_lock: bool = False
  worker_autostart: bool = True
  season_aware_research_enabled: bool = True
  recognition_pass_score: float = 0.7
  recognition_fail_score: float = 0.6
  anilist_fallback_enabled: bool = True
  anilist_fallback_timeout_seconds: float = 8.0

  # AI 识别外挂功能（默认关闭，不影响原有识别流程）
  ai_enabled: bool = False
  ai_provider: str = 'openai'          # 'openai' | 'gemini'
  ai_api_key: str = ''                 # OpenAI 兼容 API Key
  ai_base_url: str = ''                # OpenAI 兼容 API 地址（留空使用官方）
  ai_model: str = ''                   # OpenAI 模型，留空默认 gpt-4o-mini
  ai_confidence_threshold: str = 'Medium'  # 'High' | 'Medium' | 'Low'
  ai_gemini_api_key: str = ''          # Google Gemini API Key
  ai_gemini_base_url: str = ''         # Gemini 自定义地址（留空使用官方）
  ai_gemini_model: str = 'gemini-2.5-flash'

  debug: bool = False
  scan_threads: int = max(1, (os.cpu_count() or 1) * 2)

  env_file: Path = _default_env_file()
  env_prefix: str = 'AMM_'

  def __post_init__(self) -> None:
    _ensure_env_file(self.env_file)
    self.load_from_env_file()

  def load_from_env_file(self) -> None:
    # Deliberately load from .env only. Do not consume runtime OS env AMM_*.
    data = _read_env_file(self.env_file)
    p = self.env_prefix

    self.bangumi_api_key = data.get(f'{p}BANGUMI_API_KEY', self.bangumi_api_key)
    self.tmdb_api_key = data.get(f'{p}TMDB_API_KEY', self.tmdb_api_key)
    self.emby_url = data.get(f'{p}EMBY_URL', self.emby_url)
    self.emby_api_key = data.get(f'{p}EMBY_API_KEY', self.emby_api_key)
    self.emby_library_ids = data.get(f'{p}EMBY_LIBRARY_IDS', self.emby_library_ids)

    self.movie_fallback_strategy = data.get(f'{p}MOVIE_FALLBACK_STRATEGY', self.movie_fallback_strategy)
    self.movie_fallback_hints = data.get(f'{p}MOVIE_FALLBACK_HINTS', self.movie_fallback_hints)

    self.stats_ignore_specials = _parse_bool(data.get(f'{p}STATS_IGNORE_SPECIALS'), self.stats_ignore_specials)
    self.stats_ignore_extras = _parse_bool(data.get(f'{p}STATS_IGNORE_EXTRAS'), self.stats_ignore_extras)
    self.stats_ignore_trailers_featurettes = _parse_bool(
      data.get(f'{p}STATS_IGNORE_TRAILERS_FEATURETTES'),
      self.stats_ignore_trailers_featurettes,
    )

    self.auth_enabled = _parse_bool(data.get(f'{p}AUTH_ENABLED'), self.auth_enabled)
    self.auth_username = data.get(f'{p}AUTH_USERNAME', self.auth_username)
    self.auth_password = data.get(f'{p}AUTH_PASSWORD', self.auth_password)
    self.auth_secret = data.get(f'{p}AUTH_SECRET', self.auth_secret)
    self.auth_token_expire_hours = _parse_int(data.get(f'{p}AUTH_TOKEN_EXPIRE_HOURS'), self.auth_token_expire_hours)

    self.log_retention_days = _parse_int(data.get(f'{p}LOG_RETENTION_DAYS'), self.log_retention_days)
    self.log_max_task_files = _parse_int(data.get(f'{p}LOG_MAX_TASK_FILES'), self.log_max_task_files)
    self.log_cleanup_interval_seconds = _parse_int(
      data.get(f'{p}LOG_CLEANUP_INTERVAL_SECONDS'),
      self.log_cleanup_interval_seconds,
    )
    self.scan_threads = _parse_int(data.get(f'{p}SCAN_THREADS'), self.scan_threads)
    self.preserve_original_index = _parse_bool(
      data.get(f'{p}PRESERVE_ORIGINAL_INDEX'),
      self.preserve_original_index,
    )
    self.max_auto_remap_attempts = _parse_int(
      data.get(f'{p}MAX_AUTO_REMAP_ATTEMPTS'),
      self.max_auto_remap_attempts,
    )
    self.special_index_max_digits = _parse_int(
      data.get(f'{p}SPECIAL_INDEX_MAX_DIGITS'),
      self.special_index_max_digits,
    )
    self.pending_jsonl_path = _migrate_legacy_pending_path(
      data.get(f'{p}PENDING_JSONL_PATH', self.pending_jsonl_path),
      self.pending_jsonl_path,
    )
    legacy_unhandled = data.get(f'{p}UNHANDLED_JSONL_PATH')
    self.unprocessed_items_jsonl_path = _migrate_legacy_pending_path(
      data.get(
        f'{p}UNPROCESSED_ITEMS_JSONL_PATH',
        legacy_unhandled or self.unprocessed_items_jsonl_path,
      ),
      self.unprocessed_items_jsonl_path,
    )
    self.review_jsonl_path = _migrate_legacy_pending_path(
      data.get(
        f'{p}REVIEW_JSONL_PATH',
        self.review_jsonl_path,
      ),
      self.review_jsonl_path,
    )
    self.unhandled_jsonl_path = _migrate_legacy_pending_path(
      legacy_unhandled or self.unprocessed_items_jsonl_path,
      self.unprocessed_items_jsonl_path,
    )
    self.use_file_lock = _parse_bool(
      data.get(f'{p}USE_FILE_LOCK'),
      self.use_file_lock,
    )
    self.worker_autostart = _parse_bool(
      data.get(f'{p}WORKER_AUTOSTART'),
      self.worker_autostart,
    )
    self.season_aware_research_enabled = _parse_bool(
      data.get(f'{p}SEASON_AWARE_RESEARCH_ENABLED'),
      self.season_aware_research_enabled,
    )
    self.recognition_pass_score = _parse_float(
      data.get(f'{p}RECOGNITION_PASS_SCORE'),
      self.recognition_pass_score,
    )
    self.recognition_fail_score = _parse_float(
      data.get(f'{p}RECOGNITION_FAIL_SCORE'),
      self.recognition_fail_score,
    )
    self.anilist_fallback_enabled = _parse_bool(
      data.get(f'{p}ANILIST_FALLBACK_ENABLED'),
      self.anilist_fallback_enabled,
    )
    self.anilist_fallback_timeout_seconds = _parse_float(
      data.get(f'{p}ANILIST_FALLBACK_TIMEOUT_SECONDS'),
      self.anilist_fallback_timeout_seconds,
    )
    self.ai_enabled = _parse_bool(data.get(f'{p}AI_ENABLED'), self.ai_enabled)
    self.ai_provider = data.get(f'{p}AI_PROVIDER', self.ai_provider)
    self.ai_api_key = data.get(f'{p}AI_API_KEY', self.ai_api_key)
    self.ai_base_url = data.get(f'{p}AI_BASE_URL', self.ai_base_url)
    self.ai_model = data.get(f'{p}AI_MODEL', self.ai_model)
    self.ai_confidence_threshold = data.get(f'{p}AI_CONFIDENCE_THRESHOLD', self.ai_confidence_threshold)
    self.ai_gemini_api_key = data.get(f'{p}AI_GEMINI_API_KEY', self.ai_gemini_api_key)
    self.ai_gemini_base_url = data.get(f'{p}AI_GEMINI_BASE_URL', self.ai_gemini_base_url)
    self.ai_gemini_model = data.get(f'{p}AI_GEMINI_MODEL', self.ai_gemini_model)

  def save_to_env(self) -> None:
    env_path = self.env_file
    env_path.parent.mkdir(parents=True, exist_ok=True)
    existing: list[str] = []
    if env_path.exists():
      existing = env_path.read_text(encoding='utf-8').splitlines(keepends=True)
    existing_data = _read_env_file(env_path)

    prefix = self.env_prefix
    data_env_path = Path('/app/data/.env')
    # Guard: when persisted data .env already exists, do not overwrite a non-default
    # password with runtime default admin123 during unrelated config saves.
    if env_path == data_env_path and data_env_path.exists():
      persisted_password = existing_data.get(f'{prefix}AUTH_PASSWORD')
      if persisted_password and (self.auth_password or '') == 'admin123':
        self.auth_password = persisted_password

    updates = {
      f'{prefix}BANGUMI_API_KEY': self.bangumi_api_key,
      f'{prefix}TMDB_API_KEY': self.tmdb_api_key,
      f'{prefix}EMBY_URL': self.emby_url,
      f'{prefix}EMBY_API_KEY': self.emby_api_key,
      f'{prefix}EMBY_LIBRARY_IDS': self.emby_library_ids,
      f'{prefix}MOVIE_FALLBACK_STRATEGY': self.movie_fallback_strategy,
      f'{prefix}MOVIE_FALLBACK_HINTS': self.movie_fallback_hints,
      f'{prefix}STATS_IGNORE_SPECIALS': str(bool(self.stats_ignore_specials)).lower(),
      f'{prefix}STATS_IGNORE_EXTRAS': str(bool(self.stats_ignore_extras)).lower(),
      f'{prefix}STATS_IGNORE_TRAILERS_FEATURETTES': str(bool(self.stats_ignore_trailers_featurettes)).lower(),
      f'{prefix}AUTH_ENABLED': str(bool(self.auth_enabled)).lower(),
      f'{prefix}AUTH_USERNAME': self.auth_username,
      f'{prefix}AUTH_PASSWORD': self.auth_password,
      f'{prefix}AUTH_SECRET': self.auth_secret,
      f'{prefix}AUTH_TOKEN_EXPIRE_HOURS': str(int(self.auth_token_expire_hours)),
      f'{prefix}LOG_RETENTION_DAYS': str(int(self.log_retention_days)),
      f'{prefix}LOG_MAX_TASK_FILES': str(int(self.log_max_task_files)),
      f'{prefix}LOG_CLEANUP_INTERVAL_SECONDS': str(int(self.log_cleanup_interval_seconds)),
      f'{prefix}SCAN_THREADS': str(int(self.scan_threads)),
      f'{prefix}PRESERVE_ORIGINAL_INDEX': str(bool(self.preserve_original_index)).lower(),
      f'{prefix}MAX_AUTO_REMAP_ATTEMPTS': str(int(self.max_auto_remap_attempts)),
      f'{prefix}SPECIAL_INDEX_MAX_DIGITS': str(int(self.special_index_max_digits)),
      f'{prefix}PENDING_JSONL_PATH': self.pending_jsonl_path,
      f'{prefix}UNPROCESSED_ITEMS_JSONL_PATH': self.unprocessed_items_jsonl_path,
      f'{prefix}REVIEW_JSONL_PATH': self.review_jsonl_path,
      # Backward-compatible alias.
      f'{prefix}UNHANDLED_JSONL_PATH': self.unhandled_jsonl_path,
      f'{prefix}USE_FILE_LOCK': str(bool(self.use_file_lock)).lower(),
      f'{prefix}WORKER_AUTOSTART': str(bool(self.worker_autostart)).lower(),
      f'{prefix}SEASON_AWARE_RESEARCH_ENABLED': str(bool(self.season_aware_research_enabled)).lower(),
      f'{prefix}RECOGNITION_PASS_SCORE': str(float(self.recognition_pass_score)),
      f'{prefix}RECOGNITION_FAIL_SCORE': str(float(self.recognition_fail_score)),
      f'{prefix}ANILIST_FALLBACK_ENABLED': str(bool(self.anilist_fallback_enabled)).lower(),
      f'{prefix}ANILIST_FALLBACK_TIMEOUT_SECONDS': str(float(self.anilist_fallback_timeout_seconds)),
      f'{prefix}AI_ENABLED': str(bool(self.ai_enabled)).lower(),
      f'{prefix}AI_PROVIDER': self.ai_provider,
      f'{prefix}AI_API_KEY': self.ai_api_key,
      f'{prefix}AI_BASE_URL': self.ai_base_url,
      f'{prefix}AI_MODEL': self.ai_model,
      f'{prefix}AI_CONFIDENCE_THRESHOLD': self.ai_confidence_threshold,
      f'{prefix}AI_GEMINI_API_KEY': self.ai_gemini_api_key,
      f'{prefix}AI_GEMINI_BASE_URL': self.ai_gemini_base_url,
      f'{prefix}AI_GEMINI_MODEL': self.ai_gemini_model,
    }

    out: list[str] = []
    seen = set()
    for line in existing:
      stripped = line.strip()
      if not stripped or stripped.startswith('#') or '=' not in line:
        out.append(line)
        continue
      k = line.split('=', 1)[0].strip()
      if k in updates:
        out.append(f'{k}={updates[k]}\n')
        seen.add(k)
      else:
        out.append(line)

    for k, v in updates.items():
      if k not in seen:
        out.append(f'{k}={v}\n')

    env_path.write_text(''.join(out), encoding='utf-8')


settings = Settings()
